version: '3'
services:
  indicadores-app:
    image: indicadores-app:latest
    container_name: indicadores-app
    environment:
      - API_URL=https://api.cmfchile.cl/api-sbifv3/recursos_api
      - API_KEY=c6fb8477b4ccea040aa93d5c90f5b2ed5ef2dc60
    ports:
      - "4000:80"
      

